Repository IsaiahHarvi/NIDS, pull requests merged in 2024-08, with the labels that each got.

#46 45 reduce git lfs usage
  .gitignore
  data/CIC/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
  data/CIC/Friday-WorkingHours-Morning.pcap_ISCX.csv
  data/CIC/Monday-WorkingHours.pcap_ISCX.csv
  data/CIC/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
  data/CIC/Tuesday-WorkingHours.pcap_ISCX.csv
  data/CIC/Wednesday-workingHours.pcap_ISCX.csv
  scripts/get_data.sh
  scripts/setup_devcontainer.sh
Labels: priority: critical, Needs Review!!

#51 typescript container upgrades
  .devcontainer/typescript/devcontainer.json
  scripts/setup_guidev.sh
Labels: bug, priority: critical, Needs Review!!

#49 create mongo service and upgrade test_services
  .devcontainer/requirements-cpu.in
  .devcontainer/requirements-cpu.txt
  .devcontainer/requirements.in
  deploy/compose.yml
  deploy/mongo/Dockerfile
  deploy/mongo/compose.yml
  pytest.ini
  src/services/mongo/mongo.py
  tests/integration/test_services.py
Labels: priority: high, Needs Review!!

#59 58 sigh setup linting workflow and format code
  .devcontainer/requirements-cpu.in
  .devcontainer/requirements-cpu.txt
  .devcontainer/requirements.in
  .github/workflows/python-wf.yml
  .pylintrc
  pyproject.toml
  src/ai/BasicModule.py
  src/ai/DataModule.py
  src/ai/clustering.py
  src/ai/train.py
  src/grpc_/types.py
  src/grpc_/utils.py
  src/services/comms.py
  src/services/feeder/feeder.py
  src/services/logger/compose_logger.py
  src/services/model/recurrent.py
  src/services/model/residual.py
  src/services/mongo/mongo.py
  src/services/offline_feeder/offline_feeder.py
  src/services/store/to_file.py
  tests/conftest.py
  tests/integration/test_services.py
  tests/unit/test_model.py
  tests/unit/test_store.py
Labels: Needs Review!!, cleanup

#53 52-only-run-workflow-on-relevant-files
  .github/workflows/python-wf.yml
Labels: Needs Review!!, CI/CD, cleanup

#54 43 create a to db service
  .devcontainer/machine-learning/devcontainer.json
  .devcontainer/python/devcontainer.json
  deploy/mongo/compose.yml
  deploy/store/Dockerfile.to-db
  deploy/store/Dockerfile.to-file
  deploy/store/compose.yml
  deploy/store/requirements.in
  deploy/store/requirements.txt
  pytest.ini
  scripts/get_data.sh
  scripts/setup_guidev.sh
  src/grpc_/utils.py
  src/services/comms.py
  src/services/mongo/mongo.py
  src/services/store/to_db.py
  tests/unit/test_mongo.py
Labels: gRPC, Docker, Needs Review!!

#55 Init UI 3
  .gitignore
  app/client/.gitignore
  app/client/README.md
  app/client/bun.lockb
  app/client/components.json
  app/client/eslint.config.js
  app/client/index.html
  app/client/package-lock.json
  app/client/package.json
  app/client/postcss.config.js
  app/client/public/grid.svg
  app/client/public/vite.svg
  app/client/src/assets/.gitkeep
  app/client/src/components/PingPong.tsx
  app/client/src/components/mode-toggle.tsx
  app/client/src/components/navbar.tsx
  app/client/src/components/theme-provider.tsx
  app/client/src/components/topbar.tsx
  app/client/src/components/ui/button.tsx
  app/client/src/components/ui/card.tsx
  app/client/src/components/ui/chart.tsx
  app/client/src/components/ui/dropdown-menu.tsx
  app/client/src/components/ui/tooltip.tsx
  app/client/src/index.css
  app/client/src/lib/utils.ts
  app/client/src/main.tsx
  app/client/src/routeTree.gen.ts
  app/client/src/routes/__root.tsx
  app/client/src/routes/about.lazy.tsx
  app/client/src/routes/help/index.tsx
  app/client/src/routes/index.lazy.tsx
  app/client/src/routes/logs/index.tsx
  app/client/src/stores/bear-store.ts
  app/client/src/vite-env.d.ts
  app/client/tailwind.config.js
  app/client/tsconfig.app.json
  app/client/tsconfig.json
  app/client/tsconfig.node.json
  app/client/vite.config.ts
  app/server/.gitignore
  app/server/README.md
  app/server/bun.lockb
  app/server/package.json
  app/server/src/controllers/clientChangeStream.ts
  app/server/src/index.ts
  app/server/tsconfig.json
Labels: GUI

#78 remove mode_nodules from src directory and move package requirement t…
  app/client/src/routes/__root.tsx
  app/server/bun.lockb
  app/server/package.json
  bun.lockb
  node_modules/picocolors/LICENSE
  node_modules/picocolors/README.md
  node_modules/picocolors/package.json
  node_modules/picocolors/picocolors.browser.js
  node_modules/picocolors/picocolors.d.ts
  node_modules/picocolors/picocolors.js
  node_modules/picocolors/types.ts
  scripts/get_data.sh
Labels: GUI
