Repository IsaiahHarvi/NIDS, pull requests merged in 2024-09, with the labels that each got.

#85 80 setup websocket connections and listen to service collections and store data in front end
  .devcontainer/machine-learning/devcontainer.json
  .devcontainer/python/devcontainer.json
  .devcontainer/typescript/devcontainer.json
  app/client/bun.lockb
  app/client/index.html
  app/client/package.json
  app/client/src/components/navbar.tsx
  app/client/src/lib/websocket-utils.ts
  app/client/src/lib/zod-schemas/websocket-schemas.ts
  app/client/src/main.tsx
  app/client/src/middleware/WebSocketContext.tsx
  app/client/src/middleware/useWebSocket.ts
  app/client/src/routes/__root.tsx
  app/client/src/routes/index.lazy.tsx
  app/client/src/stores/services-store.ts
  app/server/bun.lockb
  app/server/package.json
  app/server/src/controllers/clientChangeStream.ts
  app/server/src/controllers/index.ts
  app/server/src/controllers/storeServicesChangeStream.ts
  app/server/src/database/index.ts
  app/server/src/index.ts
  app/server/src/routes/index.ts
  app/server/src/routes/websocketRoute.ts
  app/types/websocket-types.ts
  compose.yml
  deploy/compose.yml
  deploy/feeder/Dockerfile
  deploy/mongo/compose.yml
  deploy/mongo/init_replset.js
  scripts/setup_common.sh
  scripts/setup_guidev.sh
  src/services/store/to_db.py
  tests/integration/test_services.py
  tests/unit/test_mongo.py
Labels: GUI, priority: critical, Docker, Database

#82 extract useful features from feeder
  .devcontainer/requirements-cpu.in
  .devcontainer/requirements.in
  .devcontainer/requirements.txt
  .gitattributes
  .gitignore
  data/CIC/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
  data/CIC/test_data.csv
  data/checkpoints/RNN.ckpt
  data/checkpoints/ResidualNetwork.ckpt
  data/checkpoints/ResidualSmall.ckpt
  deploy/compose.yml
  deploy/feeder/Dockerfile
  deploy/feeder/requirements.in
  deploy/feeder/requirements.txt
  deploy/model/compose.yml
  deploy/model/requirements.txt
  deploy/offline_feeder/Dockerfile
  deploy/offline_feeder/requirements.in
  deploy/offline_feeder/requirements.txt
  dvc.yaml
  dvclive/class_map.json
  dvclive/metrics.json
  package.json
  scripts/get_data.sh
  scripts/update_deps.sh
  src/ai/BasicModule.py
  src/ai/DataModule.py
  src/ai/clustering.py
  src/ai/train.py
  src/ai/transforms.py
  src/grpc_/utils.py
  src/services/comms.py
  src/services/feeder/feeder.py
  src/services/model/model.py
  src/services/offline_feeder/offline_feeder.py
  tests/conftest.py
  tests/integration/test_services.py
  tests/unit/test_model.py
Labels: ML, Docker, Needs Review!!

#99 remove argus
  scripts/setup_common.sh
Labels: cleanup

#101 fix main workflows
  .github/workflows/deploy-wf.yml
  .github/workflows/python-wf.yml
  deploy/compose.yml
  deploy/feeder/requirements.txt
  deploy/model/requirements.txt
  deploy/webserver/Dockerfile
  src/app/client/src/components/AttackControl.tsx
  src/app/server/bun.lockb
  src/app/server/package.json
  src/app/server/src/database/index.ts
  src/app/server/tsconfig.json
  tests/integration/test_services.py
Labels: bug, priority: critical, CI/CD

#114 Update deploy job
  .github/workflows/deploy-wf.yml
  deploy/feeder/requirements.in
  deploy/feeder/requirements.txt
  deploy/offline_feeder/requirements.in
  deploy/offline_feeder/requirements.txt
  scripts/setup_git.sh
  src/ai/BasicModule.py
  src/ai/DataModule.py
  src/ai/transforms.py
  src/app/client/bun.lockb
  src/app/client/package.json
  src/app/client/src/components/NetworkFlowCard.tsx
  src/app/client/src/components/PcapAreaChart.tsx
  src/app/client/src/components/PieChart.tsx
  src/app/client/src/components/navbar.tsx
  src/app/client/src/components/pages/Dashboard.tsx
  src/app/client/src/components/topbar.tsx
  src/app/client/src/components/ui/chart.tsx
  src/app/client/src/middleware/api/functions/getFeeders.ts
  src/app/client/src/middleware/api/functions/getNeuralNetworks.ts
  src/app/client/src/middleware/api/functions/getOfflineFeeders.ts
  src/app/client/src/routeTree.gen.ts
  src/app/client/src/routes/__root.tsx
  src/app/client/src/routes/attack-control/index.tsx
  src/app/client/src/routes/dashboard/index.tsx
  src/app/client/src/stores/services-store.ts
  src/app/client/vite.config.ts
  src/app/server/bun.lockb
  src/app/server/package.json
  src/app/server/src/controllers/clientChangeStream.ts
  src/app/server/src/controllers/storeServicesChangeStream.ts
  src/app/server/src/database/index.ts
  src/app/server/src/index.ts
  src/app/server/src/lib/grpcClient.ts
  src/app/server/src/routes/index.ts
  src/app/server/src/routes/servicesRoutes.ts
  src/app/types/client-types.ts
  src/grpc_/utils.py
  src/services/comms.py
  src/services/feeder/feeder.py
  src/services/model/model.py
  src/services/offline_feeder/offline_feeder.py
  src/services/store/to_db.py
Labels: bug

#122 121 gui reflect incoming data and start to visuzalize
  .devcontainer/requirements-cpu.txt
  deploy/model/requirements.txt
  scripts/setup_pydev.sh
  scripts/setup_tsdev.sh
  src/app/client/bun.lockb
  src/app/client/package.json
  src/app/client/src/components/NetworkFlowCard.tsx
  src/app/client/src/components/NetworkTableCard.tsx
  src/app/client/src/components/NetworkTrafficLineChartCard.tsx
  src/app/client/src/components/PcapMetaDataModal.tsx
  src/app/client/src/components/PieChart.tsx
  src/app/client/src/components/navbar.tsx
  src/app/client/src/components/pages/Dashboard.tsx
  src/app/client/src/components/settingsModal.tsx
  src/app/client/src/components/ui/alert-dialog.tsx
  src/app/client/src/components/ui/card.tsx
  src/app/client/src/components/ui/dialog.tsx
  src/app/client/src/components/ui/hover-card.tsx
  src/app/client/src/components/ui/input.tsx
  src/app/client/src/components/ui/label.tsx
  src/app/client/src/components/ui/popover.tsx
  src/app/client/src/components/ui/scroll-area.tsx
  src/app/client/src/components/ui/select.tsx
  src/app/client/src/components/ui/switch.tsx
  src/app/client/src/components/ui/toast.tsx
  src/app/client/src/components/ui/toaster.tsx
  src/app/client/src/hooks/use-toast.ts
  src/app/client/src/lib/websocket-utils.ts
  src/app/client/src/middleware/api/functions/getFeeders.ts
  src/app/client/src/middleware/api/functions/getNeuralNetworks.ts
  src/app/client/src/middleware/api/functions/getOfflineFeeders.ts
  src/app/client/src/middleware/api/functions/startFeeders.ts
  src/app/client/src/middleware/api/functions/stopFeeders.ts
  src/app/client/src/middleware/rest-calls/rest-get.ts
  src/app/client/src/routes/__root.tsx
  src/app/client/vite.config.ts.timestamp-1725832408341-8d7a1fba6b151.mjs
  src/app/server/src/routes/servicesRoutes.ts
Labels: GUI
